# Generated by Django 4.1.7 on 2023-03-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('photo', models.ImageField(null=True, upload_to='img/%Y/%m/%d', verbose_name='Фото')),
                ('exist', models.BooleanField(default=True, verbose_name='На сайте?')),
            ],
            options={
                'verbose_name': 'Гаджет',
                'verbose_name_plural': 'Гаджеты',
            },
        ),
    ]
